### ISSUE TITLE
infrared and visible images pixel level registration

### ISSUE THREAD

**Issue by ysingfun** [ufukefe/DFM#3]
Hi,ufukefe!
Thank you so much for your beautiful work!
I want to use your algorithm for multi-modal image matching (infrared and visible images).May I ask what modifications I need to make.
Thanks!

**Comment by ufukefe** [comment]
Hi,
Thank you for your interest :)

Based on my observations, for multi-modal image matching, you should use the following parameters; 

enable_two_stage = False, model = 'VGG19',  bidirectional = True, ratio_th = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] (These parameters mean simply removing the ratio_thresholds (since IR-RGB matching is harder than IR-IR or RGB-RGB marching, we should loose the matches) and using only Stage-1 since (most probably) images are not planar unlike HPatches, if your images are planar then you can arrange enable_two_stage as True)

Also, again based on my observations [SuperPoint + SuperGlue](https://github.com/magicleap/SuperGluePretrainedNetwork), [Patch2Pix](https://github.com/GrumpyZhou/patch2pix) and [LoFTR](https://github.com/zju3dv/LoFTR) algoritms work well for multi-modal image matching.
